name: Bug Report

on:
  issues:
    types:
      - opened

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
    - name: Add issue template
      uses: actions/checkout@v2
      with:
        path: .github

    - name: Create issue template
      run: echo "name: Bug Report\n\non:\n  issues:\n    types:\n      - opened\n\njobs:\n  triage:\n    runs-on: ubuntu-latest\n\n    steps:\n    - name: Add issue template\n      uses: actions/checkout@v2\n      with:\n        path: .github\n\n    - name: Create issue template\n      run: echo \"---\nname: Bug Report\nabout: Create a report to help us improve\n---\n\n## Describe the Bug\nA clear and concise description of what the bug is.\n\n## Steps to Reproduce\n1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error\n\n## Expected Behavior\nA clear and concise description of what you expected to happen.\n\n## Screenshots\nIf applicable, add screenshots to help explain your problem.\n\n## Additional Context\nAdd any other context about the problem here.\" > .github/bug_report.md"

